services:
  cdmo_solvers_ambient:
    build:
      context: .
      dockerfile: Dockerfile
    image: cdmo_project
    container_name: cdmo_solvers_container
    volumes:
      - .:/cdmo
    working_dir: /cdmo
    stdin_open: true
    tty: true
